version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public # Asegúrate de que apunta a la carpeta public
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
