service: laravel

provider:
  name: aws
  region: us-east-1
  runtime: provided.al2

plugins:
  - ./vendor/bref/bref

functions:
  website:
    handler: public/index.php
    timeout: 28
    layers:
      - ${bref:layer.php-80-fpm}

resources:
  Resources:
    MyBucket:
      Type: 'AWS::S3::Bucket'
